---

- name: Apache install for Amazon Linux and Ubuntu, index.html from s3
  hosts: SERVERS
  become: True


  vars:
    object: petushok.jpg
    source: index_for_apache2.j2
    destination: /var/www/html


  tasks:

  - block: #=======AMAZON LINUX===========

      - name: Install PIP
        yum: name=python3-pip update_cache=yes

      - name: Apache2 Installation on Amazon Linux
        yum: name=httpd state=latest
  
      - name: Start and Enable
        service: name=httpd state=started enabled=yes

      - name: Get Apache2 version
        shell: httpd -v
        register: amazon_linux_version

    when: ansible_distribution == "Amazon"

  - block: #===========UBUNTU=============

      - name: PIP install
        apt: name=python3-pip update_cache=yes

      - name: Apache2 Installation on Ubuntu
        apt: name=apache2 state=latest
      
      - name: Start and Enable
        service: name=apache2 state=started enabled=yes
                  
      - name: Get Apache2 version
        shell: apache2 -v
        register: ubuntu_version

    when: ansible_distribution == "Ubuntu"

  - name: Ensure boto and boto3 modules are installed
    pip:
      name: "{{ item }}"
    with_items:
    - boto3
    - botocore
  
  - name: GET index.html template
    template: src={{ source }} dest={{ destination }}/index.html

  - name: GET image from S3
    amazon.aws.aws_s3:
      bucket: rpeklov-buck
      object: "{{ object }}"
      dest: "{{ destination }}/petushok.jpg"
      mode: get
    notify: 
    - Restart Apache2 Ubuntu
    - Restart Apache2 Amazon Linux
        
  - debug: var={{ item }} 
    loop:
    - amazon_linux_version.stdout_lines
    - ubuntu_version.stdout_lines


  handlers:

  - name: Restart Apache2 Amazon Linux
    service: name=httpd state=restarted
    when: ansible_distribution == "Amazon"

  - name: Restart Apache2 Ubuntu
    service: name=apache2 state=restarted    
    when: ansible_distribution == "Ubuntu"
